// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('check account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('check account', async function() {
    await driver.get("https://bonline.bmobile.co.tt/guest/payment/inmate")
    await driver.setRect(698, 691)
    await driver.findElement(By.id("account_number")).click()
    await driver.findElement(By.id("account_number")).sendKeys("10019")
    await driver.findElement(By.id("btn_check_account")).click()
    await driver.findElement(By.css("#success_modal .btn")).click()
  })
})
