# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCheckaccount():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkaccount(self):
    self.driver.get("https://bonline.bmobile.co.tt/guest/payment/inmate")
    self.driver.set_window_size(698, 691)
    self.driver.find_element(By.ID, "account_number").click()
    self.driver.find_element(By.ID, "account_number").send_keys("10019")
    self.driver.find_element(By.ID, "btn_check_account").click()
    self.driver.find_element(By.CSS_SELECTOR, "#success_modal .btn").click()
  
